"""L1c 引擎层 — Android 执行引擎统一契约（可替换）。

导入边界：零 `apps.*`、零 `django.*`；只依赖 `models.*` 与第三方引擎库。
上层经 DeviceSession（L2）消费本协议，不直接触碰引擎实现。
"""

from dataclasses import dataclass
from typing import Protocol

from models.ui_nodes import Node

__all__ = ["EngineCapabilities", "Node", "UiEngine"]


@dataclass
class EngineCapabilities:
    """引擎能力声明 — 上层按能力探测降级（XPath 定位为可选能力，路线 A）。"""

    xpath_locate: bool = False  # exists/get_text 是否原生支持
    toast_wait: bool = False  # wait_toast 是否原生支持
    ocr: bool = False  # 引擎自带 OCR（当前走 algorithms/vision）


class UiEngine(Protocol):
    """Android UI 引擎协议 — 稳定契约面（UI 操作原语）。

    替换引擎 = 换 registry 里的实现类；本协议与操作原语语义保持不变。
    """

    # ── 连接生命周期 ──
    def connect(self, serial: str, addr: str = "") -> None: ...
    def disconnect(self) -> None: ...
    def is_alive(self) -> bool: ...
    def reconnect(self) -> bool: ...

    # ── 感知（返回标准化数据，不泄漏引擎格式）──
    def screenshot(self) -> bytes: ...
    def dump_hierarchy(self) -> list[Node]: ...
    def app_current(self) -> dict: ...

    # ── 操作原语（用户语义："点击这些 UI 操作还是存在的"）──
    def click(self, x: int, y: int) -> None: ...
    def long_click(self, x: int, y: int, duration: float = 0.8) -> None: ...
    def swipe(self, x1: int, y1: int, x2: int, y2: int, duration: float = 0.5) -> None: ...
    def input_text(self, text: str, clear_first: bool = True) -> None: ...
    def press_key(self, key: str) -> None: ...
    def shell(self, cmd: str) -> str: ...
    def start_app(self, pkg: str) -> None: ...
    def stop_app(self, pkg: str) -> None: ...

    # ── XPath 可选能力（capabilities.xpath_locate 门控）──
    def exists(self, xpath: str, timeout: float = 0) -> bool: ...
    def get_text(self, xpath: str) -> str: ...
    def wait_toast(self, expected_text: str, timeout: float = 15) -> bool: ...

    # ── 能力声明 ──
    @property
    def capabilities(self) -> EngineCapabilities: ...
