# Generated by Django 6.0.6 on 2026-07-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0012_knowledge_sources_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('expected_keywords', models.TextField(blank=True, default='', help_text='Comma-separated keywords the answer should cover')),
                ('category', models.CharField(blank=True, default='general', help_text='e.g. 平台功能, 测试流程, 设备管理, 用例设计', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '评测问题',
                'verbose_name_plural': '评测问题',
                'db_table': 'ev_questions',
                'ordering': ['bank', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '问题试卷',
                'verbose_name_plural': '问题试卷',
                'db_table': 'ev_question_banks',
            },
        ),
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '评测中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_questions', models.IntegerField(default=0)),
                ('judge_provider', models.CharField(default='dashscope', max_length=50)),
                ('judge_model', models.CharField(default='qwen-max', max_length=100)),
                ('total_score', models.FloatField(default=0.0)),
                ('avg_relevance', models.FloatField(default=0.0)),
                ('avg_accuracy', models.FloatField(default=0.0)),
                ('avg_completeness', models.FloatField(default=0.0)),
                ('avg_conciseness', models.FloatField(default=0.0)),
                ('report_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_runs', to='ai_assistant.aiagent')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='evaluator.questionbank')),
            ],
            options={
                'verbose_name': '评测记录',
                'verbose_name_plural': '评测记录',
                'db_table': 'ev_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('agent_response', models.TextField(blank=True, default='')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('completeness_score', models.FloatField(default=0.0)),
                ('conciseness_score', models.FloatField(default=0.0)),
                ('human_relevance', models.FloatField(blank=True, null=True)),
                ('human_accuracy', models.FloatField(blank=True, null=True)),
                ('human_completeness', models.FloatField(blank=True, null=True)),
                ('human_conciseness', models.FloatField(blank=True, null=True)),
                ('human_note', models.TextField(blank=True, default='')),
                ('judge_reasoning', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='evaluator.evalrun')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluator.question')),
            ],
            options={
                'verbose_name': '评测结果',
                'verbose_name_plural': '评测结果',
                'db_table': 'ev_results',
                'ordering': ['question__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluator.questionbank'),
        ),
    ]
