# Generated by Django 6.0.6 on 2026-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalrun',
            name='framework',
            field=models.CharField(default='self', help_text='self | evalscope | deepeval | maseval', max_length=30),
        ),
    ]
