# Generated by Django 6.0.6 on 2026-07-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '报告', 'verbose_name_plural': '报告'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'verbose_name': '报告模板', 'verbose_name_plural': '报告模板'},
        ),
    ]
