# Generated by Django 6.0.6 on 2026-07-14 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workflow.workflowdirectory')),
            ],
            options={
                'verbose_name': '工作流目录',
                'verbose_name_plural': '工作流目录',
                'db_table': 'wf_directories',
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(choices=[('page_flow', '页面流'), ('test_case', '测试用例')], max_length=32)),
                ('config_json', models.TextField(default='{}')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workflow.workflowdirectory')),
            ],
            options={
                'verbose_name': '工作流文档',
                'verbose_name_plural': '工作流文档',
                'db_table': 'wf_documents',
                'indexes': [models.Index(fields=['doc_type', 'directory'], name='wf_document_doc_typ_754ed9_idx')],
            },
        ),
    ]
