# Generated by Django 6.0.6 on 2026-09-21 15:15
"""收窄 WorkflowDocument.doc_type 为仅 page_flow，并删除存量接口流文档。

**不可逆**：接口流（api_flow）唯一能承载的节点类型 ApiNode 已随元素定位的 Web/API
两域下线而移除，接口流成为无法添加任何节点的空壳类型；经确认把存量接口流文档一并删除
（变更 remove-element-locator-web-api，tasks 6b.7）。反向迁移只还原字段 choices，不还原数据。
"""

from django.db import migrations, models


def drop_api_flow_documents(apps, schema_editor):
    """删除存量接口流文档；page_flow 文档不受影响。"""
    WorkflowDocument = apps.get_model("workflow", "WorkflowDocument")
    WorkflowDocument.objects.filter(doc_type="api_flow").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_add_api_flow_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdocument',
            name='doc_type',
            field=models.CharField(choices=[('page_flow', '页面流')], max_length=32),
        ),
        migrations.RunPython(drop_api_flow_documents, migrations.RunPython.noop),
    ]
