# Generated by Django 6.0.6 on 2026-06-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('device_serial', models.CharField(default='', max_length=200)),
                ('selected_cases', models.JSONField(default=list)),
                ('loop_count', models.IntegerField(default=1)),
                ('summary', models.JSONField(default=dict)),
                ('started_at', models.CharField(default='', max_length=100)),
                ('finished_at', models.CharField(default='', max_length=100)),
                ('csv_path', models.CharField(blank=True, default='', max_length=1000)),
                ('log_path', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'db_table': 'tr_test_runs',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=200)),
                ('iteration', models.IntegerField()),
                ('result', models.CharField(max_length=50)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='test_runner.testrunrecord')),
            ],
            options={
                'db_table': 'tr_test_results',
                'indexes': [models.Index(fields=['case_id'], name='tr_test_res_case_id_6e1f01_idx'), models.Index(fields=['result'], name='tr_test_res_result_520b1b_idx')],
            },
        ),
    ]
