# Generated by Django 6.0.6 on 2026-07-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_id', models.CharField(max_length=50, unique=True)),
                ('conv_id', models.IntegerField(default=0)),
                ('phase', models.IntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=20)),
                ('requirement', models.TextField(blank=True, default='')),
                ('case_design', models.JSONField(default=list)),
                ('element_mapping', models.JSONField(default=list)),
                ('element_gaps', models.JSONField(default=list)),
                ('debug_notes', models.JSONField(default=list)),
                ('case_ids', models.JSONField(default=list)),
                ('run_id', models.CharField(blank=True, default='', max_length=200)),
                ('run_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tr_test_sop',
            },
        ),
    ]
