# Generated by Django 6.0.6 on 2026-07-07 16:13

import apps.test_runner.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0006_alter_casedirectory_options_and_more'),
        ('test_runner', '0003_case_id_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCard',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('creator', models.CharField(default='', max_length=200)),
                ('mode', models.CharField(default='immediate', max_length=20)),
                ('device_serial', models.CharField(default='', max_length=200)),
                ('case_ids', models.JSONField(default=list)),
                ('loop_count', models.IntegerField(default=1)),
                ('running', models.BooleanField(default=False)),
                ('case_items', models.JSONField(default=list)),
                ('step_states', models.JSONField(default=list)),
                ('overall_pass', models.IntegerField(default=0)),
                ('overall_fail', models.IntegerField(default=0)),
                ('logs', models.JSONField(default=list)),
                ('conclusion', models.TextField(blank=True, default='')),
                ('bug_ticket', models.TextField(blank=True, default='')),
                ('failed_steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务卡片',
                'verbose_name_plural': '任务卡片',
                'db_table': 'tr_task_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': '测试结果', 'verbose_name_plural': '测试结果'},
        ),
        migrations.AlterModelOptions(
            name='testrunrecord',
            options={'verbose_name': '测试运行记录', 'verbose_name_plural': '测试运行记录'},
        ),
        migrations.AlterModelOptions(
            name='testsop',
            options={'verbose_name': '测试SOP上下文', 'verbose_name_plural': '测试SOP上下文'},
        ),
        migrations.RemoveIndex(
            model_name='testresult',
            name='tr_test_res_case_id_6e1f01_idx',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='case',
            field=models.ForeignKey(blank=True, db_column='case_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='case_manager.testdefinition'),
        ),
        migrations.AlterField(
            model_name='testrunrecord',
            name='selected_cases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='taskcard',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_cards', to='test_runner.testrunrecord'),
        ),
    ]
