# Generated by Django 6.0.6 on 2026-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0004_taskcard_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='outcome',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
