# Generated by Django 6.0.6 on 2026-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0005_taskcard_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
