# Generated by Django 6.0.6 on 2026-07-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0006_taskcard_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='status',
            field=models.CharField(choices=[('idle', '未执行'), ('queued', '排队中'), ('running', '执行中'), ('done', '已完成')], default='idle', max_length=20),
        ),
    ]
