# Generated by Django 6.0.6 on 2026-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0007_taskcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunrecord',
            name='client_task_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
