# Generated by Django 6.0.6 on 2026-07-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0008_testrunrecord_client_task_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskcard',
            index=models.Index(fields=['status'], name='tr_task_car_status_48a7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcard',
            index=models.Index(fields=['device_serial'], name='tr_task_car_device__c7d570_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcard',
            index=models.Index(fields=['status', 'device_serial'], name='tr_task_car_status_72a643_idx'),
        ),
    ]
