# Generated by Django 6.0.6 on 2026-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0009_add_taskcard_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='interval_seconds',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='outcome',
            field=models.CharField(blank=True, choices=[('completed', '已完成'), ('stopped', '已停止'), ('interrupted', '运行中断'), ('error', '异常终止')], default='', max_length=20),
        ),
    ]
