# Generated by Django 6.0.6 on 2026-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0013_taskcard_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='task_type',
            field=models.CharField(choices=[('ui_automation', 'UI 自动化测试'), ('api_testing', 'API 测试')], default='ui_automation', help_text='Determines which executor and which case types are selectable', max_length=32),
        ),
    ]
