# Generated by Django 6.0.6 on 2026-07-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0014_add_task_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE tr_task_cards SET task_type = 'ui_automation' WHERE task_type IS NULL",
            reverse_sql="UPDATE tr_task_cards SET task_type = NULL WHERE task_type = 'ui_automation'",
        ),
    ]
