# Generated by Django 6.0.6 on 2026-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0015_fill_task_type_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='task_type',
            field=models.CharField(choices=[('ui_automation', 'Android UI 自动化测试'), ('api_testing', 'API 测试'), ('web_automation', 'Web 自动化测试')], default='ui_automation', help_text='Determines which executor and which case types are selectable', max_length=32),
        ),
    ]
