# Generated by Django 6.0.6 on 2026-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0017_fix_test_result_case_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='step_details',
            field=models.JSONField(blank=True, default=list, help_text='Per-step execution details with annotated screenshot paths'),
        ),
    ]
