#!/usr/bin/env python
"""Unified HTML test report generator - reusable across all test modules.

Usage:
    from report_generator import generate_report
    # Default Chinese:
    html_path = generate_report("Dashboard", results)
    # English:
    html_path = generate_report("Dashboard", results, lang="en")
"""

import os

from datetime import datetime


def _labels(lang="zh"):
    """Return i18n label dict. Add new languages here."""
    if lang == "en":
        return {
            "title": "{module} Functional Test Report",
            "kpi_total": "Total Cases",
            "kpi_passed": "Passed",
            "kpi_failed": "Failed",
            "kpi_rate": "Pass Rate",
            "h_cases": "Case Details",
            "h_dims": "Dimension Coverage",
            "h_bugs": "Bugs Found",
            "h_focus": "Next Test Focus",
            "th_desc": "Description",
            "th_expected": "Expected",
            "th_actual": "Actual",
            "th_result": "Result",
            "th_time": "Time",
            "th_dim": "Dimension",
            "th_cases": "Cases",
            "th_pass": "Pass",
            "th_fail": "Fail",
            "th_rate": "Rate",
            "th_coverage": "Coverage",
            "th_rec": "Recommendation",
            "rec_func": "Coverage sufficient",
            "rec_api": "Coverage sufficient",
            "rec_sec": "Add concurrency/auth tests",
            "rec_data": "Add boundary value tests",
            "rec_perf": "Optimize slow endpoints",
            "conc_ok": "All tests passed. Ready to commit.",
            "conc_minor": "Minor issues found. Most dimensions are healthy.",
            "conc_major": "{n} failures across {d} dimensions.",
            "next_ok": "No action required.",
            "next_fix": "Fix {n} failing case(s) then re-run affected dimensions.",
            "next_prio": "Prioritize P0 fixes then re-run full test suite.",
            "no_bugs": "No bugs found.",
            "bug_expected": "Expected",
            "bug_actual": "Actual",
            "bug_root": "Root cause",
            "bug_fix": "Fix suggestion",
            "focus_fix": "Fix {n} failure(s) and re-test",
            "focus_expand": "Increase coverage from {n} to 3+ cases",
            "focus_ok": "Coverage sufficient, maintain current level",
            "footer": "Generated by functional-testing skill",
            "env_label": "total",
        }
    # Default: zh
    return {
        "title": "{module} 功能测试报告",
        "kpi_total": "用例总数",
        "kpi_passed": "通过",
        "kpi_failed": "失败",
        "kpi_rate": "通过率",
        "h_cases": "用例详情",
        "h_dims": "维度覆盖",
        "h_bugs": "Bug 发现",
        "h_focus": "测试方向建议",
        "th_desc": "描述",
        "th_expected": "预期",
        "th_actual": "实际",
        "th_result": "结果",
        "th_time": "耗时",
        "th_dim": "维度",
        "th_cases": "用例数",
        "th_pass": "通过",
        "th_fail": "失败",
        "th_rate": "通过率",
        "th_coverage": "覆盖率",
        "th_rec": "建议",
        "rec_func": "覆盖充分，可适当减少",
        "rec_api": "覆盖充分",
        "rec_sec": "建议补充并发/权限测试",
        "rec_data": "建议补充边界值测试(null/超长)",
        "rec_perf": "需要优化慢查询端点",
        "conc_ok": "全部测试通过，可以提交。",
        "conc_minor": "发现少量问题，大部分维度健康。",
        "conc_major": "{n} 个失败分布在 {d} 个维度。",
        "next_ok": "无需操作。",
        "next_fix": "修复 {n} 个失败用例后重新测试受影响维度。",
        "next_prio": "优先修复 P0 问题后重新执行全量测试。",
        "no_bugs": "未发现 Bug。",
        "bug_expected": "预期",
        "bug_actual": "实际",
        "bug_root": "根因",
        "bug_fix": "修复建议",
        "focus_fix": "修复 {n} 个失败并复测",
        "focus_expand": "从 {n} 条扩充到 3+ 条",
        "focus_ok": "覆盖充分，保持当前水平",
        "footer": "由 functional-testing skill 生成",
        "env_label": "总计",
    }


# ── HTML template ──

_TEMPLATE = r"""<!DOCTYPE html>
<html lang="{html_lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title_raw}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
<style>
  :root {{
    --green:  #6fba2c; --blue:   #889df0; --yellow: #f7cd67;
    --pink:   #f8a6b2; --teal:   #19c8b9; --purple: #b39ef3;
    --orange: #f7a8c4; --brown:  #8b7355; --red:    #e85f5f;
    --bg:     #fdf8f0; --card:   #fffaf5;
    --text:   #794f27; --text2:  #9f927d;
    --radius-lg: 24px; --radius-md: 16px; --radius-sm: 10px;
    --shadow: 0 2px 12px rgba(139,115,85,.08);
    --font-display: 'Nunito', -apple-system, sans-serif;
    --font-body: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
  }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{
    font-family: var(--font-body); background: var(--bg);
    background-image: radial-gradient(ellipse at 20% 0%, rgba(136,157,240,.06) 0%, transparent 50%),
                      radial-gradient(ellipse at 80% 100%, rgba(111,186,44,.04) 0%, transparent 50%);
    color: var(--text); padding: 32px 24px; line-height: 1.6;
  }}
  .container {{ max-width: 1100px; margin: 0 auto; }}
  .header {{ text-align: center; margin-bottom: 32px; }}
  .header-icon {{ font-size: 40px; margin-bottom: 8px; }}
  h1 {{ font-family: var(--font-display); font-size: 28px; font-weight: 800; color: var(--brown); }}
  .meta {{ color: var(--text2); font-size: 13px; margin-top: 4px; }}
  .summary {{ display: grid; grid-template-columns: repeat(4,1fr); gap: 16px; margin-bottom: 28px; }}
  .kpi {{
    background: var(--card); border-radius: var(--radius-lg); padding: 20px 24px;
    box-shadow: var(--shadow); border: 1.5px solid rgba(139,115,85,.08);
    position: relative; overflow: hidden;
  }}
  .kpi::before {{
    content: ''; position: absolute; top: -12px; right: -12px;
    width: 48px; height: 48px; border-radius: 50%; opacity: .12;
  }}
  .kpi:nth-child(1)::before {{ background: var(--blue); }}
  .kpi:nth-child(2)::before {{ background: var(--green); }}
  .kpi:nth-child(3)::before {{ background: var(--red); }}
  .kpi:nth-child(4)::before {{ background: var(--yellow); }}
  .kpi-label {{ font-size: 11px; letter-spacing: .6px; color: var(--text2); font-weight: 700; }}
  .kpi-value {{ font-family: var(--font-display); font-size: 36px; font-weight: 800; margin-top: 4px; }}
  .kpi-green {{ color: var(--green); }} .kpi-red {{ color: var(--red); }}
  .kpi-blue {{ color: var(--blue); }} .kpi-yellow {{ color: var(--brown); }}
  .conclusion {{
    background: var(--card); border-radius: var(--radius-lg); padding: 20px 24px;
    margin-bottom: 28px; border-left: 5px solid var(--teal); box-shadow: var(--shadow);
  }}
  .conclusion-text {{ font-size: 15px; font-weight: 600; }}
  .conclusion-next {{ font-size: 13px; color: var(--text2); margin-top: 6px; }}
  h2 {{ font-family: var(--font-display); font-size: 18px; font-weight: 700;
    color: var(--brown); margin: 32px 0 14px; padding-left: 4px; }}
  .table-wrap {{
    background: var(--card); border-radius: var(--radius-lg); overflow: hidden;
    box-shadow: var(--shadow); margin-bottom: 20px;
  }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{
    background: linear-gradient(180deg, #faf5ed 0%, #f3ede2 100%);
    padding: 12px 14px; text-align: left; font-size: 10px;
    letter-spacing: .6px; color: var(--text2); font-weight: 700;
    border-bottom: 2px solid #e8dcc8;
  }}
  td {{ padding: 10px 14px; font-size: 13px; border-bottom: 1px solid #f3ede2; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:nth-child(even) {{ background: #fefbf7; }}
  .pass {{ color: var(--green); font-weight: 700; }} .fail {{ color: var(--red); font-weight: 700; }}
  .heatmap {{ display: flex; gap: 3px; align-items: center; }}
  .heat-bar {{ height: 14px; border-radius: 3px; min-width: 3px; }}
  .heat-green {{ background: linear-gradient(180deg, #7cc43a 0%, var(--green) 100%); }}
  .heat-red {{ background: linear-gradient(180deg, #f07070 0%, var(--red) 100%); }}
  .bug-card {{
    background: var(--card); border-radius: var(--radius-md); padding: 18px 22px;
    margin-bottom: 14px; box-shadow: var(--shadow); border-left: 5px solid var(--red);
  }}
  .bug-header {{ display: flex; gap: 10px; align-items: center; margin-bottom: 10px; flex-wrap: wrap; }}
  .bug-severity {{ font-size: 10px; font-weight: 800; padding: 3px 10px; border-radius: 20px; text-transform: uppercase; }}
  .bug-high {{ background: #fde8e8; color: var(--red); }} .bug-med {{ background: #fef3cd; color: #8a6d14; }}
  .bug-evidence {{
    font-family: 'SF Mono', 'Cascadia Code', 'Consolas', monospace; font-size: 12px;
    background: #faf7f0; padding: 10px 14px; border-radius: var(--radius-sm);
    margin: 8px 0; white-space: pre-wrap; line-height: 1.5;
  }}
  .bug-meta {{ font-size: 12px; color: var(--text2); margin-top: 4px; }}
  .focus-list {{ list-style: none; display: flex; flex-direction: column; gap: 8px; }}
  .focus-item {{ display: flex; gap: 14px; align-items: center; padding: 10px 16px;
    background: var(--card); border-radius: var(--radius-sm); box-shadow: var(--shadow); }}
  .focus-prio {{ font-family: var(--font-display); font-weight: 800; font-size: 12px;
    padding: 4px 10px; border-radius: 20px; min-width: 36px; text-align: center; }}
  .prio-p0 {{ background: #fde8e8; color: var(--red); }}
  .prio-p1 {{ background: #fef3cd; color: #8a6d14; }}
  .prio-p2 {{ background: #e8f0fe; color: var(--blue); }}
  .footer {{ text-align: center; color: var(--text2); font-size: 11px; margin-top: 40px;
    padding-top: 20px; border-top: 2px dashed #e8dcc8; }}
  .footer-leaf {{ display: inline-block; animation: sway 2s ease-in-out infinite; }}
  @keyframes sway {{ 0%,100% {{ transform: rotate(-3deg); }} 50% {{ transform: rotate(3deg); }} }}
  @media (max-width: 768px) {{ .summary {{ grid-template-columns: repeat(2,1fr); }} body {{ padding: 16px; }} }}
  @media print {{ body {{ background: #fff; }} .summary {{ break-inside: avoid; }} }}
</style>
</head>
<body>
<div class="container">
<div class="header">
  <div class="header-icon">{header_icon}</div>
  <h1>{title}</h1>
  <div class="meta">{timestamp} &middot; {env} &middot; {total_ms}ms {env_label}</div>
</div>
<div class="summary">
  <div class="kpi"><div class="kpi-label">{kpi_total}</div><div class="kpi-value kpi-blue">{total}</div></div>
  <div class="kpi"><div class="kpi-label">{kpi_passed}</div><div class="kpi-value kpi-green">{passed}</div></div>
  <div class="kpi"><div class="kpi-label">{kpi_failed}</div><div class="kpi-value kpi-red">{failed}</div></div>
  <div class="kpi"><div class="kpi-label">{kpi_rate}</div><div class="kpi-value kpi-yellow">{pct}%</div></div>
</div>
<div class="conclusion">
  <div class="conclusion-text">{conclusion}</div>
  <div class="conclusion-next">{next_label}: {next_action}</div>
</div>
<!-- Context -->
<div class="conclusion" style="border-left-color:var(--blue)">
  <div style="font-size:14px;font-weight:600;margin-bottom:6px">{context_title}</div>
  <div style="font-size:13px;color:var(--text2)">{context_body}</div>
</div>

<h2>{h_cases}</h2>
<div class="table-wrap"><table>
<thead><tr><th>#</th><th>Case ID</th><th>Dim</th><th>{th_desc}</th><th>{th_expected}</th><th>{th_actual}</th><th>{th_result}</th><th>{th_time}</th></tr></thead>
<tbody>{case_rows}</tbody>
</table></div>
<h2>{h_dims}</h2>
<div class="table-wrap"><table>
<thead><tr><th>{th_dim}</th><th>{th_cases}</th><th>{th_pass}</th><th>{th_fail}</th><th>{th_rate}</th><th>{th_coverage}</th><th>{th_rec}</th></tr></thead>
<tbody>{dim_rows}</tbody>
</table></div>
{bugs_section}
<h2>{h_focus}</h2>
<ul class="focus-list">{focus_items}</ul>
<div class="footer"><span class="footer-leaf">{footer_icon}</span> {footer} &middot; {timestamp}</div>
</div>
</body>
</html>"""


def generate_report(
    module_name, results, lang="zh", env="Django:8765 + Vite:5173 + MySQL", output_dir=None
):
    """Generate an HTML test report.

    Args:
        module_name: Module under test (e.g. "Dashboard")
        results: [{case, dim, status, duration_ms, error, evidence: {actual, expected}}, ...]
        lang: "zh" (default) or "en"
        env: Environment description
        output_dir: Save path. Default: tests/functional/{module}/reports/

    Returns:
        Path to the generated HTML file
    """
    L = _labels(lang)
    total = len(results)
    passed = sum(1 for r in results if r["status"] == "PASS")
    failed = total - passed
    pct = round(passed / total * 100) if total > 0 else 0
    total_ms = sum(r["duration_ms"] for r in results)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    dims = _summarize_dimensions(results)
    if failed == 0:
        conclusion = L["conc_ok"]
        next_action = L["next_ok"]
    elif all(d["total"] - d["passed"] <= 1 for d in dims.values()):
        conclusion = L["conc_minor"]
        next_action = L["next_fix"].format(n=failed)
    else:
        bad_dims = sum(1 for d in dims.values() if d["passed"] < d["total"])
        conclusion = L["conc_major"].format(n=failed, d=bad_dims)
        next_action = L["next_prio"]

    rate_color = "green" if pct >= 90 else ("red" if pct < 70 else "yellow")
    next_label = "Next" if lang == "en" else "下一步"

    # Module context — explains what this module does to non-technical readers
    _MODULE_CONTEXT = {
        "Dashboard": (
            "测试范围：仪表盘首页的统计概览功能",
            "仪表盘是用户登录后看到的第一个页面，展示 6 项核心统计：在线设备、"
            "测试用例、页面元素、执行记录、智能体数量、测试报告。"
            "本次测试验证所有统计数据与源模块保持一致，接口安全可靠，页面加载速度达标。",
        ),
        "AI-Assistant": (
            "测试范围：AI 助手的智能体管理功能",
            "AI 助手是用户与 AI 交互的核心模块，支持创建智能体、对话交流、"
            "知识库检索、测试用例自动生成。本次测试验证智能体的增删改查与数据库同步。",
        ),
    }
    ctx = _MODULE_CONTEXT.get(
        module_name, (f"{module_name}", f"对 {module_name} 模块进行五维功能测试")
    )
    context_title, context_body = ctx

    # Case rows — show human-readable title, not cryptic case IDs
    case_rows = []
    for i, r in enumerate(results, 1):
        ev = r.get("evidence", {})
        expected = (ev.get("expected") or "OK")[:40]
        actual = (ev.get("actual") or "OK")[:40]
        status_cls = "pass" if r["status"] == "PASS" else "fail"
        status_text = "PASS" if r["status"] == "PASS" else "FAIL"
        title = r.get("title", r["case"])  # Use human-readable title if available
        desc = r.get("description", "")
        title_html = f"<strong>{_esc(title)}</strong>"
        if desc:
            title_html += f'<br><span style="font-size:11px;color:var(--text2)">{_esc(desc)}</span>'
        case_rows.append(
            f'<tr><td>{i}</td><td style="font-size:11px">{r["case"]}</td><td>{r["dim"]}</td>'
            f"<td>{title_html}</td>"
            f'<td style="font-size:11px">{_esc(expected)}</td>'
            f'<td style="font-size:11px">{_esc(actual)}</td>'
            f'<td class="{status_cls}">{status_text}</td>'
            f"<td>{r['duration_ms']}ms</td></tr>"
        )

    # Dimension rows
    rec_keys = {
        "FUNC": "rec_func",
        "API": "rec_api",
        "SEC": "rec_sec",
        "DATA": "rec_data",
        "PERF": "rec_perf",
    }
    dim_rows = []
    for dim_name in ["FUNC", "API", "SEC", "DATA", "PERF"]:
        if dim_name not in dims:
            continue
        d = dims[dim_name]
        dpct = round(d["passed"] / d["total"] * 100) if d["total"] > 0 else 0
        green_bars = max(1, int(dpct / 100 * 30))
        red_bars = 30 - green_bars
        heat_html = (
            f'<span class="heat-bar heat-green" style="width:{green_bars * 4}px"></span>'
            + (
                f'<span class="heat-bar heat-red" style="width:{red_bars * 4}px"></span>'
                if red_bars > 0
                else ""
            )
        )
        dim_rows.append(
            f"<tr><td><strong>{dim_name}</strong></td><td>{d['total']}</td>"
            f'<td style="color:var(--green)">{d["passed"]}</td>'
            f'<td style="color:var(--red)">{d["total"] - d["passed"]}</td>'
            f'<td>{dpct}%</td><td><div class="heatmap">{heat_html}</div></td>'
            f'<td style="font-size:12px">{L[rec_keys.get(dim_name, "rec_func")]}</td></tr>'
        )

    # Bugs
    bugs_found = [r for r in results if r["status"] == "FAIL"]
    if bugs_found:
        bug_cards = []
        for i, b in enumerate(bugs_found, 1):
            sev = "HIGH" if b.get("bug_type") == "CodeBug" else "MED"
            sev_cls = "bug-high" if sev == "HIGH" else "bug-med"
            ev = b.get("evidence", {})
            bug_cards.append(
                f'<div class="bug-card">'
                f'<div class="bug-header">'
                f'<span class="bug-severity {sev_cls}">{sev}</span>'
                f"<span>{b['bug_type']}</span>"
                f"<strong>{b['case']}</strong>"
                f'<span style="color:var(--text2)">({b["dim"]})</span>'
                f"</div>"
                f'<div class="bug-evidence">{_esc(b.get("error", "No details"))}</div>'
                f'<div class="bug-meta">'
                f"{L['bug_expected']}: {_esc(ev.get('expected', 'N/A'))}"
                f" | {L['bug_actual']}: {_esc(ev.get('actual', 'N/A'))}"
                f"</div></div>"
            )
        bugs_section = f"<h2>{L['h_bugs']}</h2>\n" + "\n".join(bug_cards)
    else:
        bugs_section = f'<h2>{L["h_bugs"]}</h2>\n<p style="color:var(--green);font-size:14px">{L["no_bugs"]}</p>'

    # Focus items
    focus_items = []
    for dim_name in ["FUNC", "API", "SEC", "DATA", "PERF"]:
        if dim_name not in dims:
            continue
        d = dims[dim_name]
        if d["passed"] < d["total"]:
            prio, cls = "P0", "prio-p0"
            action = L["focus_fix"].format(n=d["total"] - d["passed"])
        elif d["total"] < 3:
            prio, cls = "P1", "prio-p1"
            action = L["focus_expand"].format(n=d["total"])
        else:
            prio, cls = "P2", "prio-p2"
            action = L["focus_ok"]
        focus_items.append(
            f'<li class="focus-item"><span class="focus-prio {cls}">{prio}</span>'
            f"<strong>{dim_name}</strong>: {action}</li>"
        )

    # Fill template
    html = _TEMPLATE.format(
        html_lang="zh-CN" if lang == "zh" else "en",
        title=L["title"].format(module=module_name),
        title_raw=f"{module_name} Test Report",
        header_icon="🍃" if lang == "zh" else "📊",
        footer_icon="🍃" if lang == "zh" else "📊",
        timestamp=timestamp,
        env=env,
        total_ms=total_ms,
        env_label=L["env_label"],
        kpi_total=L["kpi_total"],
        kpi_passed=L["kpi_passed"],
        kpi_failed=L["kpi_failed"],
        kpi_rate=L["kpi_rate"],
        total=total,
        passed=passed,
        failed=failed,
        pct=pct,
        conclusion=conclusion,
        next_action=next_action,
        next_label=next_label,
        h_cases=L["h_cases"],
        h_dims=L["h_dims"],
        h_focus=L["h_focus"],
        th_desc=L["th_desc"],
        th_expected=L["th_expected"],
        th_actual=L["th_actual"],
        th_result=L["th_result"],
        th_time=L["th_time"],
        th_dim=L["th_dim"],
        th_cases=L["th_cases"],
        th_pass=L["th_pass"],
        th_fail=L["th_fail"],
        th_rate=L["th_rate"],
        th_coverage=L["th_coverage"],
        th_rec=L["th_rec"],
        case_rows="\n".join(case_rows),
        dim_rows="\n".join(dim_rows),
        bugs_section=bugs_section,
        focus_items="\n".join(focus_items),
        context_title=context_title,
        context_body=context_body,
        footer=L["footer"],
    )

    # Write to file
    if output_dir is None:
        output_dir = os.path.join(
            os.getcwd(), "tests", "functional", module_name.lower().replace(" ", "-"), "reports"
        )
    os.makedirs(output_dir, exist_ok=True)
    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)

    # Also write latest
    latest_path = os.path.join(output_dir, "report_latest.html")
    with open(latest_path, "w", encoding="utf-8") as f:
        f.write(html)

    return filepath


def _summarize_dimensions(results):
    dims = {}
    for r in results:
        d = r["dim"]
        if d not in dims:
            dims[d] = {"total": 0, "passed": 0}
        dims[d]["total"] += 1
        if r["status"] == "PASS":
            dims[d]["passed"] += 1
    return dims


def _desc_for(case_id):
    parts = case_id.split("-")
    if len(parts) >= 3:
        return f"{parts[0]} {parts[1]} #{parts[2]}"
    return case_id


def _esc(text):
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
