"""evaluator DRF ViewSets — bank CRUD, run lifecycle, human scoring."""

import threading

from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import NotFound
from rest_framework.response import Response

from apps.ai_assistant.models import AIAgent

from . import api
from .models import EvalResult, EvalRun, QuestionBank
from .serializers import (
    EvalResultSerializer,
    EvalRunListSerializer,
    EvalRunSerializer,
    QuestionBankSerializer,
)


class QuestionBankViewSet(viewsets.ModelViewSet):
    """Question bank CRUD — standard REST + ``seed`` action.

    Endpoints (auto-generated by router):
        GET    /banks/        → list
        POST   /banks/        → create (with nested questions)
        GET    /banks/{id}/   → retrieve
        PUT    /banks/{id}/   → update (full replacement)
        PATCH  /banks/{id}/   → partial update
        DELETE /banks/{id}/   → destroy

    Custom actions:
        POST   /banks/seed/   → create default 30-question bank
    """

    serializer_class = QuestionBankSerializer

    def get_queryset(self):
        return QuestionBank.objects.prefetch_related("questions").order_by("-updated_at")

    def perform_destroy(self, instance):
        """DELETE /banks/{id}/ —— 写经 api.py（题目由 FK 级联删除）。"""
        api.delete_question_bank(instance.id)

    @action(detail=False, methods=["post"])
    def seed(self, request):
        """POST /banks/seed/ — create the default 30-question bank."""
        result = api.seed_default_bank()
        if result["existed"]:
            return Response(
                {
                    "id": result["id"],
                    "message": "默认试卷已存在，直接返回",
                }
            )
        return Response(
            {
                "id": result["id"],
                "question_count": result["question_count"],
            }
        )


class EvalRunViewSet(viewsets.ModelViewSet):
    """Evaluation run lifecycle — list, create, retrieve, destroy, start.

    Endpoints:
        GET    /runs/          → list (summary)
        POST   /runs/          → create (record only, does not start an evaluation)
        GET    /runs/{id}/     → retrieve (with results)
        DELETE /runs/{id}/     → destroy

    Custom actions:
        POST   /runs/start/    → launch evaluation in background thread
    """

    http_method_names = ["get", "post", "delete", "head", "options"]

    def get_serializer_class(self):
        if self.action == "list":
            return EvalRunListSerializer
        return EvalRunSerializer

    def get_queryset(self):
        qs = EvalRun.objects.select_related("agent", "bank")
        if self.action == "list":
            # 列表最多 50 条（API-评估器.md §4.1）；切片只限 list ——
            # 详情动作若拿到已切片查询集，按 pk 过滤会抛 TypeError，被 DRF 转成 404。
            return qs.order_by("-created_at")[:50]
        if self.action == "retrieve":
            return qs.prefetch_related("results__question")
        return qs

    def perform_create(self, serializer):
        """POST /runs/ —— 只落库一条 EvalRun 记录，不触发评估；写经 api.py。

        agent_id / bank_id 可选（EvalRun.agent / bank 可空，见 API-评估器.md §4.2）；
        给定但不存在时报 404（文案与 start 动作一致），不静默落 NULL。
        """
        data = dict(serializer.validated_data)

        agent_id = data.get("agent_id")
        agent = None
        if agent_id:
            try:
                agent = AIAgent.objects.get(id=agent_id)
            except AIAgent.DoesNotExist:
                raise NotFound("agent not found")

        bank_id = data.get("bank_id")
        bank = None
        if bank_id:
            try:
                bank = QuestionBank.objects.get(id=bank_id)
            except QuestionBank.DoesNotExist:
                raise NotFound("question bank not found")

        result = api.create_eval_run(
            agent=agent,
            bank=bank,
            framework=data.get("framework", "self"),
            judge_provider=data.get("judge_provider", "dashscope"),
            judge_model=data.get("judge_model", "qwen-max"),
        )
        # api 不返回 ORM（calibration §6 规则 4），故按 id 只读回取供响应序列化
        serializer.instance = EvalRun.objects.get(id=result["id"])

    def perform_destroy(self, instance):
        """DELETE /runs/{id}/ —— 写经 api.py（逐题结果由 FK 级联删除）。"""
        api.delete_eval_run(instance.id)

    @action(detail=False, methods=["post"])
    def start(self, request):
        """POST /runs/start/ — launch a new evaluation in background thread."""
        agent_id = request.data.get("agent_id")
        bank_id = request.data.get("bank_id")
        framework = request.data.get("framework", "self")
        judge_provider = request.data.get("judge_provider", "dashscope")
        judge_model = request.data.get("judge_model", "qwen-max")

        if not agent_id or not bank_id:
            return Response(
                {"message": "agent_id and bank_id are required"},
                status=400,
            )

        try:
            agent = AIAgent.objects.get(id=agent_id)
        except AIAgent.DoesNotExist:
            return Response({"message": "agent not found"}, status=404)

        try:
            bank = QuestionBank.objects.get(id=bank_id)
        except QuestionBank.DoesNotExist:
            return Response({"message": "question bank not found"}, status=404)

        run_id = api.create_eval_run(
            agent=agent,
            bank=bank,
            framework=framework,
            judge_provider=judge_provider,
            judge_model=judge_model,
        )["id"]

        if framework and framework != "self":
            self._start_external_framework(run_id, agent, bank, framework)
        else:
            self._start_self_evaluator(run_id, judge_provider, judge_model)

        return Response(
            {
                "run": {"id": run_id},
                "message": f"评测已开始，共 {bank.question_count} 题",
            }
        )

    def _start_external_framework(self, run_id, agent, bank, framework):
        """Launch evaluation via an external framework adapter (evalscope/deepeval/maseval)."""
        from .frameworks import get_adapter

        def _bg():
            try:
                adapter = get_adapter(framework)
                if adapter is None:
                    api.mark_eval_run_failed(run_id, f"Unknown framework: {framework}")
                    return

                import asyncio

                from apps.ai_assistant.api import decrypt_key, get_provider_config

                api_key = decrypt_key(agent.api_key) if agent.api_key else ""
                provider_cfg = get_provider_config(agent.model_provider, agent.base_url)

                agent_config = {
                    "model_provider": agent.model_provider,
                    "model_name": agent.model_name,
                    "api_key": api_key,
                    "base_url": provider_cfg.get("base_url", ""),
                }
                questions_list = [
                    {
                        "content": q.content,
                        "expected_keywords": q.expected_keywords,
                        "category": q.category,
                    }
                    for q in bank.questions.all().order_by("order", "id")
                ]
                result = asyncio.run(adapter.run(agent_config, questions_list))
                api.finish_external_eval_run(
                    run_id,
                    status="completed" if result.ok else "failed",
                    total_score=result.total_score,
                    total_questions=len(questions_list),
                    completed_questions=len(result.items),
                    report={
                        "framework": framework,
                        "total_score": result.total_score,
                        "scores": result.scores,
                        "items": result.items,
                        "raw": result.raw,
                        "message": result.error if not result.ok else "",
                    },
                )
            except Exception as e:
                api.mark_eval_run_failed(run_id, str(e))

        t = threading.Thread(target=_bg, daemon=True)
        t.start()

    def _start_self_evaluator(self, run_id, judge_provider, judge_model):
        """Launch evaluation via the built-in LLM-as-Judge evaluator."""
        from .evaluator import run_evaluation

        def _bg():
            try:
                run_evaluation(run_id, judge_provider, judge_model)
            except Exception as e:
                api.mark_eval_run_failed(run_id, str(e))

        t = threading.Thread(target=_bg, daemon=True)
        t.start()


class EvalResultViewSet(viewsets.ReadOnlyModelViewSet):
    """Read-only access to individual evaluation results.

    Endpoints:
        GET  /results/        → list
        GET  /results/{id}/   → retrieve
    """

    serializer_class = EvalResultSerializer

    def get_queryset(self):
        return EvalResult.objects.select_related("question").order_by(
            "run", "question__order", "id"
        )

    @action(detail=True, methods=["post"], url_path="score")
    def submit_score(self, request, pk=None):
        """POST /results/{id}/score/ — submit human scores for a result."""
        result = self.get_object()
        api.submit_human_score(result.id, request.data)
        return Response({"result_id": result.id, "scored": True})
