# Generated by Django 6.0.6 on 2026-07-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="case_manager.casedirectory",
                    ),
                ),
            ],
            options={
                "db_table": "cm_case_directories",
                "unique_together": {("parent", "name")},
            },
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_definitions",
                to="case_manager.casedirectory",
            ),
        ),
    ]
