# Generated by Django 6.0.6 on 2026-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_manager", "0002_casedirectory_testdefinition_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdefinition",
            name="design_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="五法之一：场景流法 / 等价类边界值 / 判定表 / 正交排列 / 错误推测",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="expected_result",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="metrics",
            field=models.TextField(blank=True, default="", help_text="量化指标"),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="precondition",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="priority",
            field=models.CharField(
                choices=[("P0", "P0 — 必测"), ("P1", "P1 — 应测"), ("P2", "P2 — 可测")],
                default="P1",
                max_length=4,
            ),
        ),
    ]
