# Generated by Django 6.0.6 on 2026-07-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0003_testdefinition_iot_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCaseCache',
        ),
    ]
