# Generated by Django 6.0.6 on 2026-07-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0005_testdefinition_unique_directory_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casedirectory',
            options={'verbose_name': '用例目录', 'verbose_name_plural': '用例目录'},
        ),
        migrations.AlterModelOptions(
            name='testdefinition',
            options={'verbose_name': '用例定义', 'verbose_name_plural': '用例定义'},
        ),
    ]
