# Generated by Django 6.0.6 on 2026-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0006_alter_casedirectory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdefinition',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='editing_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='editing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
