# Generated by Django 6.0.6 on 2026-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0008_add_case_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdefinition',
            name='permitted_users',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='visibility',
            field=models.CharField(choices=[('public', '所有人可见'), ('hidden', '仅创建者'), ('restricted', '指定用户')], default='public', max_length=20),
        ),
    ]
