# Generated by Django 6.0.6 on 2026-07-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0009_add_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedirectory',
            name='allow_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casedirectory',
            name='allow_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casedirectory',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='permission',
            field=models.CharField(choices=[('edit', '所有人可编辑'), ('readonly', '所有人只读'), ('restricted', '指定用户可编辑')], default='edit', max_length=20),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='permitted_editors',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
