# Generated by Django 6.0.6 on 2026-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0010_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdefinition',
            name='watchers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
