# Generated by Django 6.0.6 on 2026-07-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0011_add_watchers_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdefinition',
            name='case_type',
            field=models.CharField(default='ui_automation', help_text='ui_automation / storage / api_testing', max_length=32),
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('case_type', models.CharField(default='api_testing', max_length=32)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('P0', 'P0 — 必测'), ('P1', 'P1 — 应测'), ('P2', 'P2 — 可测')], default='P1', max_length=4)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('url', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('expected_status', models.IntegerField(default=200)),
                ('expected_response', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('pre_script', models.TextField(blank=True, default='')),
                ('post_script', models.TextField(blank=True, default='')),
                ('design_method', models.CharField(blank=True, default='', max_length=100)),
                ('precondition', models.TextField(blank=True, default='')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('metrics', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
                ('editing_by', models.CharField(blank=True, default='', max_length=200)),
                ('editing_since', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', '所有人可见'), ('hidden', '仅创建者'), ('restricted', '指定用户')], default='public', max_length=20)),
                ('permitted_users', models.TextField(blank=True, default='[]')),
                ('permission', models.CharField(choices=[('edit', '所有人可编辑'), ('readonly', '所有人只读'), ('restricted', '指定用户可编辑')], default='edit', max_length=20)),
                ('permitted_editors', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_testcases', to='case_manager.casedirectory')),
            ],
            options={
                'verbose_name': 'API 接口测试用例',
                'verbose_name_plural': 'API 接口测试用例',
                'db_table': 'cm_api_testcases',
                'constraints': [models.UniqueConstraint(fields=('directory', 'title'), name='unique_api_directory_title')],
            },
        ),
        migrations.CreateModel(
            name='StorageTestCase',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('case_type', models.CharField(default='storage', max_length=32)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('P0', 'P0 — 必测'), ('P1', 'P1 — 应测'), ('P2', 'P2 — 可测')], default='P1', max_length=4)),
                ('data_schema', models.JSONField(blank=True, default=dict)),
                ('operations', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('expected_data', models.JSONField(blank=True, default=dict)),
                ('design_method', models.CharField(blank=True, default='', max_length=100)),
                ('precondition', models.TextField(blank=True, default='')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('metrics', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
                ('editing_by', models.CharField(blank=True, default='', max_length=200)),
                ('editing_since', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', '所有人可见'), ('hidden', '仅创建者'), ('restricted', '指定用户')], default='public', max_length=20)),
                ('permitted_users', models.TextField(blank=True, default='[]')),
                ('permission', models.CharField(choices=[('edit', '所有人可编辑'), ('readonly', '所有人只读'), ('restricted', '指定用户可编辑')], default='edit', max_length=20)),
                ('permitted_editors', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_testcases', to='case_manager.casedirectory')),
            ],
            options={
                'verbose_name': '存储业务功能测试用例',
                'verbose_name_plural': '存储业务功能测试用例',
                'db_table': 'cm_storage_testcases',
                'constraints': [models.UniqueConstraint(fields=('directory', 'title'), name='unique_storage_directory_title')],
            },
        ),
    ]
