# Generated by Django 6.0.6 on 2026-07-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0012_add_case_type_and_new_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casedirectory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='casedirectory',
            name='case_type',
            field=models.CharField(default='ui_automation', help_text='ui_automation / storage / api_testing — each module has independent tree', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='casedirectory',
            constraint=models.UniqueConstraint(fields=('parent', 'name', 'case_type'), name='unique_directory_parent_name_type'),
        ),
    ]
