# Generated by Django 6.0.6 on 2026-07-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0013_add_case_type_to_directory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagetestcase',
            options={'verbose_name': '功能测试用例', 'verbose_name_plural': '功能测试用例'},
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='assertions',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='expected_result',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='expected_status',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='http_method',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='post_script',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='pre_script',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='request_body',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='url',
        ),
        migrations.RemoveField(
            model_name='storagetestcase',
            name='data_schema',
        ),
        migrations.RemoveField(
            model_name='storagetestcase',
            name='expected_data',
        ),
        migrations.RemoveField(
            model_name='storagetestcase',
            name='operations',
        ),
        migrations.RemoveField(
            model_name='storagetestcase',
            name='validation_rules',
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='请求体'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='custom_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='自定义列'),
        ),
        migrations.AddField(
            model_name='storagetestcase',
            name='custom_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='自定义列'),
        ),
        migrations.AddField(
            model_name='storagetestcase',
            name='steps',
            field=models.TextField(blank=True, default='', verbose_name='用例步骤'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='expected_response',
            field=models.TextField(blank=True, default='', verbose_name='预期响应文本'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='headers',
            field=models.TextField(blank=True, default='', verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='precondition',
            field=models.TextField(blank=True, default='', verbose_name='前置条件'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0 — 必测'), ('P1', 'P1 — 应测'), ('P2', 'P2 — 可测')], default='P1', max_length=4, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='title',
            field=models.CharField(max_length=500, verbose_name='用例标题'),
        ),
        migrations.AlterField(
            model_name='storagetestcase',
            name='expected_result',
            field=models.TextField(blank=True, default='', verbose_name='预期结果'),
        ),
        migrations.AlterField(
            model_name='storagetestcase',
            name='precondition',
            field=models.TextField(blank=True, default='', verbose_name='前置条件'),
        ),
        migrations.AlterField(
            model_name='storagetestcase',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0 — 必测'), ('P1', 'P1 — 应测'), ('P2', 'P2 — 可测')], default='P1', max_length=4, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='storagetestcase',
            name='title',
            field=models.CharField(max_length=500, verbose_name='用例标题'),
        ),
    ]
