# Generated by Django 6.0.6 on 2026-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0014_simplify_storage_and_api_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='rows',
            field=models.JSONField(blank=True, default=list, verbose_name='表格行数据'),
        ),
        migrations.AddField(
            model_name='storagetestcase',
            name='rows',
            field=models.JSONField(blank=True, default=list, verbose_name='表格行数据'),
        ),
    ]
