# Generated by Django 6.0.6 on 2026-07-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0015_add_rows_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTestCase',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='用例标题')),
                ('case_type', models.CharField(default='web_automation', max_length=32)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('priority', models.CharField(choices=[('P0', 'P0 — 必测'), ('P1', 'P1 — 应测'), ('P2', 'P2 — 可测')], default='P1', max_length=4, verbose_name='优先级')),
                ('url', models.TextField(blank=True, default='', verbose_name='目标 URL')),
                ('precondition', models.TextField(blank=True, default='', verbose_name='前置条件')),
                ('steps', models.TextField(blank=True, default='', verbose_name='操作步骤')),
                ('expected_result', models.TextField(blank=True, default='', verbose_name='预期结果')),
                ('custom_columns', models.JSONField(blank=True, default=list, verbose_name='自定义列')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='表格行数据')),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('design_method', models.CharField(blank=True, default='', max_length=100)),
                ('metrics', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
                ('editing_by', models.CharField(blank=True, default='', max_length=200)),
                ('editing_since', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', '所有人可见'), ('hidden', '仅创建者'), ('restricted', '指定用户')], default='public', max_length=20)),
                ('permitted_users', models.TextField(blank=True, default='[]')),
                ('permission', models.CharField(choices=[('edit', '所有人可编辑'), ('readonly', '所有人只读'), ('restricted', '指定用户可编辑')], default='edit', max_length=20)),
                ('permitted_editors', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_testcases', to='case_manager.casedirectory')),
            ],
            options={
                'verbose_name': 'Web 自动化测试用例',
                'verbose_name_plural': 'Web 自动化测试用例',
                'db_table': 'cm_web_testcases',
                'constraints': [models.UniqueConstraint(fields=('directory', 'title'), name='unique_web_directory_title')],
            },
        ),
    ]
