# Generated by Django 6.0.6 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0017_add_api_url_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='assertions',
            field=models.JSONField(blank=True, default=list, verbose_name='自定义断言'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='expected_status',
            field=models.IntegerField(default=200, verbose_name='预期HTTP状态码'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='steps_json',
            field=models.TextField(blank=True, default='[]', verbose_name='结构化步骤JSON'),
        ),
        migrations.AddField(
            model_name='webtestcase',
            name='steps_json',
            field=models.TextField(blank=True, default='[]', verbose_name='结构化步骤JSON'),
        ),
    ]
