# Generated by Django 6.0.6 on 2026-08-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0018_add_steps_json_to_api_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitestcase',
            name='assertions',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='body',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='custom_columns',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='design_method',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='expected_response',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='expected_status',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='method',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='steps_json',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='url',
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='config_json',
            field=models.JSONField(default=dict, verbose_name='统一 JSON 配置'),
        ),
    ]
