# Generated by Django 6.0.6 on 2026-07-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='compression_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='compression_keep_recent',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='compression_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='compression_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='compression_threshold',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='enable_meta_tool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='enable_rewrite_query',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='formatter',
            field=models.CharField(default='dashscope', max_length=50),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='generate_kwargs',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='long_term_memory_mode',
            field=models.CharField(default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='max_iters',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='memory_mode',
            field=models.CharField(default='inmemory', max_length=20),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='parallel_tool_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='print_hint_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='tts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
