# Generated by Django 6.0.6 on 2026-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_v2_agentscope_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='available_models',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
