# Generated by Django 6.0.6 on 2026-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aiagent_available_models_aiagent_is_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='agent_scope_session_id',
            field=models.CharField(blank=True, default='', help_text='AgentScope session ID for SSE streaming', max_length=200),
        ),
    ]
