# Generated by Django 6.0.6 on 2026-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_aiagent_agent_scope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='blocks',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='reason',
            field=models.CharField(blank=True, default='normal', max_length=30),
        ),
    ]
