# Generated by Django 6.0.6 on 2026-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_add_content_blocks_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='key_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
