# Generated by Django 6.0.6 on 2026-07-13 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_add_key_revealed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiagent',
            options={'verbose_name': '智能体', 'verbose_name_plural': '智能体'},
        ),
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'verbose_name': '对话', 'verbose_name_plural': '对话'},
        ),
        migrations.AlterModelOptions(
            name='aiexecutionlog',
            options={'ordering': ['-created_at'], 'verbose_name': '执行日志', 'verbose_name_plural': '执行日志'},
        ),
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['created_at'], 'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterModelOptions(
            name='aitask',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelOptions(
            name='aitool',
            options={'verbose_name': '工具配置', 'verbose_name_plural': '工具配置'},
        ),
        migrations.AddField(
            model_name='aiagent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
