# Generated by Django 6.0.6 on 2026-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_add_owner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='enable_knowledge_base',
            field=models.BooleanField(default=True),
        ),
    ]
