# Generated by Django 6.0.6 on 2026-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0009_add_knowledge_base_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='parallel_tool_calls',
            field=models.BooleanField(default=True),
        ),
    ]
