# Generated by Django 6.0.6 on 2026-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0014_aimessage_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='agent_scope_credential_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='credential_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
