# Generated by Django 6.0.6 on 2026-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0015_add_credential_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISharedTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('config_json', models.TextField(default='{}')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '共享工具',
                'verbose_name_plural': '共享工具',
                'db_table': 'ai_shared_tools',
            },
        ),
    ]
