# Generated by Django 6.0.6 on 2026-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0017_avatar_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='knowledge_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
