# Generated by Django 6.0.6 on 2026-07-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0018_alter_aiagent_knowledge_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiagent',
            name='phase_tool_config',
        ),
    ]
