# Generated by Django 6.0.6 on 2026-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0019_remove_aiagent_phase_tool_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='enable_business_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='enable_mcp_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='enable_skills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='enable_workspace_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='enable_knowledge_base',
            field=models.BooleanField(default=False),
        ),
    ]
