# Generated by Django 6.0.6 on 2026-08-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0020_add_capability_toggles'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE ai_agents ALTER COLUMN enable_workspace_tools SET DEFAULT 0",
                "ALTER TABLE ai_agents ALTER COLUMN enable_business_tools SET DEFAULT 0",
                "ALTER TABLE ai_agents ALTER COLUMN enable_mcp_tools SET DEFAULT 0",
                "ALTER TABLE ai_agents ALTER COLUMN enable_skills SET DEFAULT 0",
                "ALTER TABLE ai_agents ALTER COLUMN enable_knowledge_base SET DEFAULT 0",
            ],
            reverse_sql=[
                "ALTER TABLE ai_agents ALTER COLUMN enable_workspace_tools DROP DEFAULT",
                "ALTER TABLE ai_agents ALTER COLUMN enable_business_tools DROP DEFAULT",
                "ALTER TABLE ai_agents ALTER COLUMN enable_mcp_tools DROP DEFAULT",
                "ALTER TABLE ai_agents ALTER COLUMN enable_skills DROP DEFAULT",
                "ALTER TABLE ai_agents ALTER COLUMN enable_knowledge_base DROP DEFAULT",
            ],
        ),
    ]
