# Generated by Django 6.0.6 on 2026-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0021_add_capability_db_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='max_iters',
            field=models.IntegerField(default=20),
        ),
    ]
