# Generated by Django 6.0.6 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0022_alter_aiagent_max_iters'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='cache_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='cache_creation_input_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
