# Generated by Django 6.0.6 on 2026-08-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0023_add_aimessage_cache_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiagent',
            name='agent_scope_credential_id',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='credential_hash',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='enable_meta_tool',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='enable_rewrite_query',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='formatter',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='long_term_memory_mode',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='memory_mode',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='print_hint_msg',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='tts_enabled',
        ),
    ]
