# Generated by Django 6.0.6 on 2026-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0024_remove_aiagent_agent_scope_credential_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlatformTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '平台业务工具开关',
                'verbose_name_plural': '平台业务工具开关',
                'db_table': 'ai_platform_tools',
            },
        ),
    ]
