# Generated by Django 6.0.6 on 2026-08-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0026_remove_legacy_platform_tools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AITool',
        ),
    ]
