# Generated by Django 6.0.6 on 2026-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0027_remove_ai_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='vision_model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
