# Generated by Django 6.0.6 on 2026-08-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0028_aiagent_vision_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiagent',
            name='compression_enabled',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='compression_keep_recent',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='compression_prompt',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='compression_template',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='compression_threshold',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='generate_kwargs',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='max_iters',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='parallel_tool_calls',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='temperature',
        ),
    ]
