# Generated by Django 6.0.6 on 2026-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0029_remove_aiagent_compression_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='strong_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='strong_model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
