# Generated by Django 6.0.6 on 2026-08-28（手动生成：字段与 models.py 一致）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0032_aiagent_max_loops'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='device_serial',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
