# Generated by Django 6.0.6 on 2026-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0033_aitask_device_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='cache_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitask',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitask',
            name='model_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aitask',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
