# Generated by Django 6.0.6 on 2026-09-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0034_aitask_cache_input_tokens_aitask_input_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitask',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='aitask',
            name='report_name',
        ),
        migrations.RemoveField(
            model_name='aitask',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='aitask',
            name='route',
        ),
    ]
