# Generated by Django 6.0.6（手动生成：沙箱禁用 makemigrations 的子进程，字段与 models.py 一致）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0035_remove_aitask_checklist_remove_aitask_report_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitask",
            name="by_role",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
