# Generated by Django 6.0.6 on 2026-09-23 11:22

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0041_add_planner_page_flow_guidance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDevicePromptArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("auto", "自动"), ("permanent", "永久")],
                        default="auto",
                        max_length=16,
                    ),
                ),
                ("planner", models.TextField(blank=True, default="")),
                ("executor", models.TextField(blank=True, default="")),
                ("verifier", models.TextField(blank=True, default="")),
                ("created_by", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_archives",
                        to="ai_assistant.aiagent",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备提示词存档",
                "verbose_name_plural": "设备提示词存档",
                "db_table": "ai_device_prompt_archives",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["agent", "kind", "-created_at"], name="ai_dpa_agent_kind_idx"
                    )
                ],
            },
        ),
    ]
