# Generated by Django 6.0.6 on 2026-09-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0042_aidevicepromptarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiagent',
            name='enable_knowledge_base',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='knowledge_sources',
        ),
    ]
