# Generated by Django 6.0.6 on 2026-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0044_add_verifier_log_evidence_guidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILogPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField(unique=True)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('baud', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '日志端口监听开关',
                'verbose_name_plural': '日志端口监听开关',
                'db_table': 'ai_log_ports',
                'ordering': ['port'],
            },
        ),
    ]
