# Generated by Django 6.0.6 on 2026-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0050_verifier_log_check_contract'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aidevicepromptarchive',
            name='ai_dpa_agent_kind_idx',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='prompt_executor',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='prompt_planner',
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='prompt_verifier',
        ),
        migrations.DeleteModel(
            name='AIDevicePromptArchive',
        ),
    ]
