# Generated by Django 6.0.6 on 2026-06-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('package', models.CharField(blank=True, default='', max_length=500)),
                ('activity', models.CharField(blank=True, default='', max_length=500)),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=1000)),
                ('element_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_locator_pages', to='device_pool.device')),
            ],
            options={
                'db_table': 'el_pages',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, default='', max_length=500)),
                ('text_val', models.CharField(blank=True, default='', max_length=2000)),
                ('content_desc', models.CharField(blank=True, default='', max_length=2000)),
                ('resource_id', models.CharField(blank=True, default='', max_length=500)),
                ('bounds', models.CharField(blank=True, default='', max_length=200)),
                ('xpath_candidates', models.TextField(default='[]')),
                ('clickable', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('is_test_point', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='element_locator.page')),
            ],
            options={
                'db_table': 'el_elements',
            },
        ),
        migrations.CreateModel(
            name='PageFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_action', models.CharField(default='click', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='element_locator.page')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='element_locator.page')),
                ('trigger_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_flows', to='element_locator.element')),
            ],
            options={
                'db_table': 'el_page_flows',
            },
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('page', 'resource_id', 'bounds'), name='uq_el_element_page_attrs'),
        ),
    ]
