# Generated by Django 6.0.6 on 2026-07-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='label',
            field=models.CharField(blank=True, default='', max_length=500, unique=True),
        ),
    ]
