# Generated by Django 6.0.6 on 2026-07-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0003_page_parent_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': '元素', 'verbose_name_plural': '元素'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': '页面', 'verbose_name_plural': '页面'},
        ),
        migrations.AlterModelOptions(
            name='pageflow',
            options={'verbose_name': '页面跳转流', 'verbose_name_plural': '页面跳转流'},
        ),
    ]
