# Generated by Django 6.0.6 on 2026-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_pool', '0004_alter_device_options_alter_devicelock_options_and_more'),
        ('element_locator', '0004_alter_element_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='is_test_point',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_folder',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='label',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['parent_id', 'label'], name='idx_el_pages_parent_label'),
        ),
    ]
