# Generated by Django 6.0.6 on 2026-07-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='元素名称')),
                ('locator_type', models.CharField(choices=[('css_selector', 'CSS Selector'), ('xpath', 'XPath'), ('id', 'ID'), ('class_name', 'Class Name'), ('name', 'Name'), ('tag_name', 'Tag Name'), ('link_text', 'Link Text'), ('partial_link_text', 'Partial Link Text'), ('text', 'Text Content'), ('test_id', 'Test ID (data-testid)'), ('role', 'ARIA Role'), ('placeholder', 'Placeholder')], default='css_selector', max_length=50, verbose_name='定位方式')),
                ('locator_value', models.TextField(default='', verbose_name='定位表达式')),
                ('page_url', models.TextField(blank=True, default='', verbose_name='页面 URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='元素描述')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='标签')),
                ('is_test_point', models.BooleanField(db_index=True, default=False, verbose_name='测试点')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Web 元素',
                'verbose_name_plural': 'Web 元素',
                'db_table': 'el_web_elements',
            },
        ),
    ]
