# Generated by Django 6.0.6 on 2026-07-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0006_webelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='分组名称')),
                ('is_folder', models.BooleanField(db_index=True, default=False, verbose_name='仅作目录')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='element_locator.webgroup')),
            ],
            options={
                'verbose_name': 'Web 分组',
                'verbose_name_plural': 'Web 分组',
                'db_table': 'el_web_groups',
            },
        ),
        migrations.AddField(
            model_name='webelement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='element_locator.webgroup', verbose_name='所属分组'),
        ),
    ]
