# Generated by Django 6.0.6 on 2026-07-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0007_webgroup_webelement_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_action', models.CharField(default='click', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='element_locator.webgroup')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='element_locator.webgroup')),
                ('trigger_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_web_flows', to='element_locator.webelement')),
            ],
            options={
                'verbose_name': 'Web 页面跳转流',
                'verbose_name_plural': 'Web 页面跳转流',
                'db_table': 'el_web_page_flows',
            },
        ),
    ]
