# Generated by Django 6.0.6 on 2026-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0008_webpageflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(default='', verbose_name='接口 URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_body_schema', models.JSONField(blank=True, default=dict, verbose_name='请求体结构')),
                ('response_body_schema', models.JSONField(blank=True, default=dict, verbose_name='响应体结构')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='标签')),
                ('is_test_point', models.BooleanField(db_index=True, default=False, verbose_name='测试点')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API 接口',
                'verbose_name_plural': 'API 接口',
                'db_table': 'el_api_endpoints',
            },
        ),
    ]
