# Generated by Django 6.0.6 on 2026-07-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0009_apiendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='分组名称')),
                ('is_folder', models.BooleanField(db_index=True, default=False, verbose_name='仅作目录')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='element_locator.apigroup')),
            ],
            options={
                'verbose_name': 'API 分组',
                'verbose_name_plural': 'API 分组',
                'db_table': 'el_api_groups',
            },
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='element_locator.apigroup', verbose_name='所属分组'),
        ),
    ]
