# Generated by Django 6.0.6 on 2026-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0010_apigroup_apiendpoint_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='element',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='index',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='element',
            name='scrollable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='element',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='element',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='ocr_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='page',
            name='snapshot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
