# Generated by Django 6.0.6 on 2026-09-09 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_locator', '0011_element_checked_element_depth_element_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocatorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('android', 'Android'), ('web', 'Web'), ('api', 'API')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '定位项目',
                'verbose_name_plural': '定位项目',
                'db_table': 'el_locator_projects',
            },
        ),
        migrations.CreateModel(
            name='LocatorDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='element_locator.locatordirectory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='element_locator.locatorproject')),
            ],
            options={
                'verbose_name': '定位目录',
                'verbose_name_plural': '定位目录',
                'db_table': 'el_locator_directories',
            },
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_endpoints', to='element_locator.locatordirectory', verbose_name='所属目录'),
        ),
        migrations.AddField(
            model_name='page',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='element_locator.locatordirectory'),
        ),
        migrations.AddField(
            model_name='webelement',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_elements', to='element_locator.locatordirectory', verbose_name='所属目录'),
        ),
        migrations.AddIndex(
            model_name='locatordirectory',
            index=models.Index(fields=['project', 'parent', 'sort_order'], name='idx_el_dir_proj_parent'),
        ),
        migrations.AddConstraint(
            model_name='locatordirectory',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='uq_el_directory_project_parent_name'),
        ),
    ]
