# Generated by Django 6.0.6 on 2026-09-21 15:08
"""元素定位 Web/API 两域下线：删除 5 个模型及其表，并移除 web / api 两个系统项目。

**不可逆**：本迁移 DROP 掉 el_web_groups / el_web_elements / el_api_groups /
el_api_endpoints / el_web_page_flows 五张表，其中数据一并丢失。
应用前必须已执行 `python manage.py dumpdata element_locator` 留档
（变更 remove-element-locator-web-api 的 tasks 1.1）。
"""

from django.db import migrations, models


def remove_web_api_projects(apps, schema_editor):
    """删除 web / api 两个系统项目；其 LocatorDirectory 经 FK CASCADE 一并清除。

    `Page.directory` 与 `WebElement.directory` 都是 SET_NULL，故页面不会被连带删除；
    五张 Web/API 表由本迁移随后的 DeleteModel 操作删除。
    """
    LocatorProject = apps.get_model("element_locator", "LocatorProject")
    LocatorProject.objects.filter(code__in=["web", "api"]).delete()


def restore_project_rows(apps, schema_editor):
    """反向迁移只把两个项目行补回，不恢复任何 Web/API 数据。"""
    LocatorProject = apps.get_model("element_locator", "LocatorProject")
    for code, name in (("web", "Web"), ("api", "API")):
        LocatorProject.objects.get_or_create(code=code, defaults={"name": name, "description": ""})


class Migration(migrations.Migration):
    dependencies = [
        ("element_locator", "0014_clear_page_ocr_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apigroup",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="webelement",
            name="directory",
        ),
        migrations.RemoveField(
            model_name="webelement",
            name="group",
        ),
        migrations.RemoveField(
            model_name="webpageflow",
            name="trigger_element",
        ),
        migrations.RemoveField(
            model_name="webgroup",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="webpageflow",
            name="from_group",
        ),
        migrations.RemoveField(
            model_name="webpageflow",
            name="to_group",
        ),
        migrations.AlterField(
            model_name="locatorproject",
            name="code",
            field=models.CharField(choices=[("android", "Android")], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name="ApiEndpoint",
        ),
        migrations.DeleteModel(
            name="ApiGroup",
        ),
        migrations.DeleteModel(
            name="WebElement",
        ),
        migrations.DeleteModel(
            name="WebGroup",
        ),
        migrations.DeleteModel(
            name="WebPageFlow",
        ),
        # 放在 DeleteModel 之后：此时 el_web_elements 已不存在，删项目只会级联到 el_locator_directories
        migrations.RunPython(remove_web_api_projects, restore_project_rows),
    ]
