# Generated by Django 6.0.6 on 2026-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("element_locator", "0015_remove_apigroup_parent_remove_webelement_directory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="checkable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="element",
            name="focusable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="element",
            name="long_clickable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="element",
            name="primary_stable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="element",
            name="primary_xpath",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="element",
            name="seq",
            field=models.IntegerField(default=0),
        ),
    ]
