# Generated by Django 6.0.6 on 2026-08-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_pool', '0006_device_added_by_device_connected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, default='', max_length=100)),
                ('method', models.CharField(default='both', max_length=10)),
                ('dump_json', models.JSONField(blank=True, default=dict)),
                ('ocr_json', models.JSONField(blank=True, default=dict)),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=1000)),
                ('package', models.CharField(blank=True, default='', max_length=500)),
                ('activity', models.CharField(blank=True, default='', max_length=500)),
                ('screen_w', models.IntegerField(default=0)),
                ('screen_h', models.IntegerField(default=0)),
                ('element_count', models.IntegerField(default=0)),
                ('actionable_count', models.IntegerField(default=0)),
                ('ocr_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector_snapshots', to='device_pool.device')),
            ],
            options={
                'verbose_name': '检查器快照',
                'verbose_name_plural': '检查器快照',
                'db_table': 'di_snapshots',
                'indexes': [models.Index(fields=['created_at'], name='di_snapshot_created_7e4a98_idx'), models.Index(fields=['device_id'], name='di_snapshot_device__9cbb1d_idx')],
            },
        ),
    ]
