# Generated by Django 6.0.6 on 2026-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='method',
            field=models.CharField(default='dump', max_length=10),
        ),
    ]
