# Generated by Django 6.0.6 on 2026-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_inspector', '0002_alter_snapshot_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='nodes_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
