# Generated by Django 6.0.6 on 2026-06-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("status", models.CharField(default="ONLINE", max_length=20)),
                ("locked_by", models.CharField(blank=True, default="", max_length=200)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dp_devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("timeout_seconds", models.IntegerField(default=300)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locks",
                        to="device_pool.device",
                    ),
                ),
            ],
            options={
                "db_table": "dp_device_locks",
            },
        ),
    ]
