# Generated by Django 6.0.6 on 2026-06-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_pool", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="waiting", max_length=20)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dp_device_queue",
                "ordering": ["requested_at"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="android_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="device",
            name="connection_type",
            field=models.CharField(default="USB", max_length=10),
        ),
        migrations.AddField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="device",
            name="screen_h",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="screen_w",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="devicelock",
            name="release_reason",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="devicelock",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicelock",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="dp_devices_status_47e1d0_idx"),
        ),
        migrations.AddIndex(
            model_name="devicelock",
            index=models.Index(fields=["device", "status"], name="dp_device_l_device__4b3c95_idx"),
        ),
        migrations.AddField(
            model_name="devicequeue",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_entries",
                to="device_pool.device",
            ),
        ),
    ]
