# Generated by Django 6.0.6 on 2026-07-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_pool", "0002_v2_full_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="occupied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="occupied_by",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="devicelock",
            name="lock_type",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
