# Generated by Django 6.0.6 on 2026-07-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_pool', '0003_add_occupy_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterModelOptions(
            name='devicelock',
            options={'verbose_name': '设备锁', 'verbose_name_plural': '设备锁'},
        ),
        migrations.AlterModelOptions(
            name='devicequeue',
            options={'ordering': ['requested_at'], 'verbose_name': '设备队列', 'verbose_name_plural': '设备队列'},
        ),
    ]
