# Generated by Django 6.0.6 on 2026-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_pool', '0004_alter_device_options_alter_devicelock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelock',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='devicelock',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('device',), name='uq_device_active_lock'),
        ),
    ]
