# Generated by Django 6.0.6 on 2026-08-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_pool', '0005_add_locks_heartbeat_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='added_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='connection_addr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='DeviceQueue',
        ),
    ]
