"""case_manager test fixtures — sample config_json, endpoint constants."""

import time
import uuid

import allure
import pytest
import requests

# ── Endpoint constants ──

API_DEFS_URL = "/api/cases/api-testing/definitions"
LOGIN_URL = "/api/auth/login"


# ── Helpers ──


def _make_case_id() -> str:
    """Generate a unique API test case ID."""
    return f"API-TEST-{int(time.time() * 1000)}-{uuid.uuid4().hex[:4]}"


# ── Sample data ──


@pytest.fixture(scope="session")
def auth_token(base_url: str) -> dict:
    """Login as admin and return access + refresh tokens."""
    resp = requests.post(
        f"{base_url}{LOGIN_URL}",
        json={"username": "admin", "password": "admin123"},
        timeout=10,
    )
    body = resp.json()
    assert body.get("status") is True, f"Login failed: {body}"
    data = body["data"]
    return {
        "access_token": data["access_token"],
        "refresh_token": data["refresh_token"],
    }


@pytest.fixture
def auth_headers(auth_token: dict) -> dict:
    """Authorization header for authenticated API calls."""
    return {"Authorization": f"Bearer {auth_token['access_token']}"}


@pytest.fixture
def sample_config_json() -> dict:
    """Return a minimal but valid config_json suitable for CRUD testing."""
    return {
        "case_info": {
            "id": _make_case_id(),
            "title": f"Pytest API Test {uuid.uuid4().hex[:6]}",
            "description": "Auto-generated by pytest",
            "precondition": "",
        },
        "steps": [
            {
                "name": "Echo GET",
                "domain": "https://httpbin.org",
                "url": "/get",
                "method": "GET",
                "headers": {"Accept": "application/json"},
                "body": {},
                "request_schema": None,
                "response_schema": None,
                "extract": [],
                "assert": False,
            }
        ],
        "test_data": [],
        "validation": [],
    }


@pytest.fixture
def full_config_json() -> dict:
    """Return a comprehensive config_json with all optional fields populated."""
    return {
        "case_info": {
            "id": _make_case_id(),
            "title": f"Full API Test {uuid.uuid4().hex[:6]}",
            "description": "Comprehensive test with schemas, extract, test_data, validation",
            "precondition": "1. 目标服务已启动\n2. 测试用户已注册",
        },
        "steps": [
            {
                "name": "登录获取Token",
                "domain": "https://httpbin.org",
                "url": "/post",
                "method": "POST",
                "headers": {"Content-Type": "application/json"},
                "body": {"username": "{{username}}", "password": "{{password}}"},
                "request_schema": {
                    "type": "object",
                    "required": ["username", "password"],
                    "properties": {
                        "username": {"type": "string", "minLength": 3},
                        "password": {"type": "string", "minLength": 6},
                    },
                },
                "response_schema": {
                    "type": "object",
                    "required": ["json"],
                    "properties": {
                        "json": {
                            "type": "object",
                            "required": ["username"],
                            "properties": {
                                "username": {"const": "{{username}}"},
                            },
                        }
                    },
                },
                "extract": [{"name": "echo_data", "path": "$.json"}],
                "assert": True,
            },
            {
                "name": "带Token请求",
                "domain": "https://httpbin.org",
                "url": "/get",
                "method": "GET",
                "headers": {"Authorization": "Bearer {{token}}"},
                "body": {},
                "request_schema": None,
                "response_schema": {
                    "type": "object",
                    "required": ["headers"],
                    "properties": {
                        "headers": {"type": "object"},
                    },
                },
                "extract": [],
                "assert": True,
            },
        ],
        "test_data": [
            {
                "input": {"username": "admin", "password": "admin123"},
                "output_schema": {
                    "step_index": 0,
                    "schema": {
                        "type": "object",
                        "required": ["json"],
                        "properties": {
                            "json": {
                                "type": "object",
                                "required": ["username"],
                                "properties": {"username": {"const": "admin"}},
                            }
                        },
                    },
                },
            },
            {
                "input": {"username": "guest", "password": "guest456"},
                "output_schema": None,
            },
        ],
        "validation": [
            {
                "step_index": 0,
                "enabled": True,
                "schema": {
                    "type": "object",
                    "required": ["username", "password"],
                    "properties": {
                        "username": {"type": "string", "minLength": 3},
                        "password": {"type": "string", "minLength": 6},
                    },
                },
            },
            {
                "step_index": 1,
                "enabled": False,
                "schema": None,
            },
        ],
    }


# ── Allure helper ──


def set_allure_metadata(
    feature: str,
    story: str,
    title: str,
    description: str,
    severity: str,
    tags: tuple[str, ...],
) -> None:
    """Single-call Allure metadata helper."""
    allure.dynamic.feature(feature)
    allure.dynamic.story(story)
    allure.dynamic.title(title)
    allure.dynamic.description(description)
    allure.dynamic.severity(getattr(allure.severity_level, severity.upper()))
    allure.dynamic.tag(*tags)
